services:
  postgres:
    image: postgres:16-alpine
    container_name: barbearia-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: barbearia
      POSTGRES_PASSWORD: barbearia123
      POSTGRES_DB: barbearia_comanda
      

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
